---
- name: IaC Workshop - Add Pod Fabrics
  hosts: ndfc
  gather_facts: false
  connection: httpapi
  collections:
    - cisco.dcnm
  vars:
    pod_num: 2
  tasks:
  - name: Build 1st DC JSON Payload from Template
    vars:
      dc_num: 1
      mgmt_gw: "100.64.20{{pod_num}}.1"
    set_fact:
      payload: "{{ lookup('ansible.builtin.template', './fabric_json.j2') | to_json }}"
  - name: JSON Payload
    ansible.builtin.debug:
      msg: "{{ payload }}"
  - name: POST New Fabric JSON
    dcnm_rest:
      method: POST
      path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics
      json_data: "{{ payload }}"
    ignore_errors: true
  - name: Build 2nd DC JSON Payload from Template
    vars:
      dc_num: 2
      mgmt_gw: "100.64.20{{pod_num}}.65"
    set_fact:
      payload: "{{ lookup('ansible.builtin.template', './fabric_json.j2') | to_json }}"
  - name: JSON Payload
    ansible.builtin.debug:
      msg: "{{ payload }}"
  - name: POST New Fabric JSON
    dcnm_rest:
      method: POST
      path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics
      json_data: "{{ payload }}"
    ignore_errors: true
  - name: Build External Fabric JSON Payload from Template
    set_fact:
      payload: "{{ lookup('ansible.builtin.template', './ext_json.j2') | to_json }}"
  - name: JSON Payload
    ansible.builtin.debug:
      msg: "{{ payload }}"
  - name: POST External Fabric JSON
    dcnm_rest:
      method: POST
      path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics
      json_data: "{{ payload }}"  # - name: Result
    ignore_errors: true
  #   ansible.builtin.debug:
  #     msg: "{{ result }}"
