---
- name: IaC Workshop - Trigger Build & Deploy Configuration for Fabrics
  hosts: ndfc
  gather_facts: false
  connection: httpapi
  collections:
    - cisco.dcnm
  vars:
    pod_num: 1
  tasks:
    - name: Config and Deploy DC1
      vars:
        dc_num: 1
      include_tasks: config-deploy-fabric-tasks.yaml
    - name: Config and Deploy DC2
      vars:
        dc_num: 2
      include_tasks: config-deploy-fabric-tasks.yaml
