---
- name: IaC Workshop - Remove Switches from Fabric
  hosts: ndfc
  gather_facts: false
  connection: httpapi
  collections:
    - cisco.dcnm
  vars_prompt:
    - name: pod_num
      prompt: Enter Pod number to delete
      private: no
  vars:
    ansible_command_timeout: 1000 # requried for dcnm_inventory
    ansible_connect_timeout: 1000 # requried for dcnm_inventory
  tasks:
    - name: Confirm Deletion
      pause:
        prompt: "Are you sure you want remove all the switches in NDFC for Pod #{{pod_num}}? (yes/no)"
      register: confirm_delete
    - name: Remove Switches from DC1
      dcnm_inventory:
        fabric: "AUTO-POD{{pod_num}}-DC1"
        state: deleted # merged / deleted / overridden / query
        config:
          ## DC1-SPINE1
        - seed_ip: "100.64.20{{pod_num}}.2"
          ## DC1-SPINE2
        - seed_ip: "100.64.20{{pod_num}}.3"
          ## DC1-LEAF1
        - seed_ip: "100.64.20{{pod_num}}.4"
          ## DC1-LEAF2
        - seed_ip: "100.64.20{{pod_num}}.5"
          ## DC1-ABGW1
        - seed_ip: "100.64.20{{pod_num}}.6"
          ## DC1-ABGW2
        - seed_ip: "100.64.20{{pod_num}}.7"
      when: confirm_delete.user_input | bool
    - name: Remove Switches to DC2
      dcnm_inventory:
        fabric: "AUTO-POD{{pod_num}}-DC2"
        state: deleted # merged / deleted / overridden / query
        config:
          ## DC2-VBGW1
        - seed_ip: "100.64.20{{pod_num}}.66"
          ## DC2-VBGW1
        - seed_ip: "100.64.20{{pod_num}}.67"
      when: confirm_delete.user_input | bool
    - block:
        - name: Query WAN Switch Details
          dcnm_rest:
            method: GET
            path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/AUTO-POD{{pod_num}}-WAN/inventory/switchesByFabric"
          register: results
        - name: Display Results
          debug:
            msg: "{{results.response.DATA}}"
        - name: Extract WAN Switch UUID
          set_fact:
            switch_uuid: "{{results.response.DATA[0].swUUID}}"
        - name: Remove WAN Switch
          dcnm_rest:
            method: DELETE
            path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/AUTO-POD{{pod_num}}-WAN/switches/UUID/{{switch_uuid}}"
            data: "{{ payload | to_json }}"
      when: confirm_delete.user_input | bool
