- name: Prompt for Serial Number
  pause:
    prompt: "Please enter serial number for {{switch.name}} (i.e. 97NYUVAU6R4)?"
  register: serialNumber
- debug:
    msg: "{{serialNumber}}"
- name: set_fact when serialNumber found
  ansible.builtin.set_fact:
    data: "{{item.data}}"
    fingerprint: "{{item.fingerprint}}"
    publicKey: "{{item.publicKey}}"
  loop: "{{ response.DATA }}"
  # when: "'{{serialNumber}}' in item.serialNumber" # {{switch.serialNumber}}
  when: serialNumber.user_input in item.serialNumber
- name: Create POAP Definition
  set_fact:
    payload:
      - serialNumber: "{{serialNumber.user_input}}" # {{switch.serialNumber}}
        model: "N9K-C9300v"
        version: "10.2(3)"
        hostname: "{{switch.name}}"
        ipAddress: "{{switch.mgmt_ip}}"
        password: "{{password}}"
        discoveryAuthProtocol: 0
        data: "{{data | to_json }}"
        fingerprint: "{{fingerprint}}"
        publicKey: "{{publicKey}}"
        reAdd: false
        imagePolicy: ""
        role: "{{switch.role}}"
  when: data is defined
- name: JSON Payload
  ansible.builtin.debug:
    msg: "{{ payload }}"
  when: data is defined
- name: POST New Fabric JSON
  dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/AUTO-POD{{pod_num}}-DC{{dc_num}}/inventory/poap"
    data: "{{ payload | to_json }}"
  when: payload is defined
