- name: Prompt for First Serial Number
  pause:
    prompt: "Please enter {{first_switch}} serial number (i.e. 97NYUVAU6R4)?"
  register: peerOneId
- name: Prompt for Second Serial Number
  pause:
    prompt: "Please enter {{second_switch}} serial number (i.e. 97NYUVAU6R4)?"
  register: peerTwoId
- name: Build JSON Payload
  set_fact:
    payload:
      peerOneId: "{{peerOneId.user_input}}"
      peerTwoId: "{{peerTwoId.user_input}}"
      useVirtualPeerlink: false
- name: JSON Payload
  ansible.builtin.debug:
    msg: "{{ payload }}"
- name: POST vPC Pairing JSON
  vars:
    dc_num: 1
  dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/vpcpair"
    data: "{{ payload | to_json }}"
  ignore_errors: true
