- name: Build JSON Payload
  set_fact:
    payload:
      peerOneId: "{{pair.peerOneId}}"
      peerTwoId: "{{pair.peerTwoId}}"
      useVirtualPeerlink: false
- name: JSON Payload
  ansible.builtin.debug:
    msg: "{{ payload | to_json }}"
- name: POST vPC Pairing JSON
  vars:
    dc_num: 1
  dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/vpcpair"
    data: "{{ payload | to_json }}"
