- name: POST Config Save
  dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/AUTO-POD{{pod_num}}-MSD/config-save"
    data: null
- name: Pause for 2 minutes
  ansible.builtin.pause:
    minutes: 2
- name: POST Config Deploy
  dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/AUTO-POD{{pod_num}}-DC{{dc_num}}/config-deploy"
    data: null
  ignore_errors: yes
