---
- name: IaC Workshop - Add Switches to Fabrics
  hosts: ndfc
  gather_facts: false
  connection: httpapi
  collections:
    - cisco.dcnm
  vars:
    pod_num: 1
  tasks:
    - name: GET POAP Device List
      vars:
        dc_num: 1
      dcnm_rest:
        method: GET
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/AUTO-POD{{pod_num}}-DC{{dc_num}}/inventory/poap"
      register: devices
    - name: Extract Response
      set_fact:
        response: "{{devices.response}}"
    # - name: Add Switches to DC1
    #   vars:
    #     dc_num: 1
    #     password: "C!sco123"
    #     switches:
    #       # - name: DC1-SPINE1
    #       #   serialNumber: 9ACSWFLK2YN
    #       #   role: spine
    #       #   mgmt_ip: 100.64.201.2
    #       # - name: DC1-SPINE2
    #       #   serialNumber: 9CXIRUKTTHQ
    #       #   role: spine
    #       #   mgmt_ip: 100.64.201.3
    #       # - name: DC1-LEAF1
    #       #   serialNumber: 9JV0UUSBF8I
    #       #   role: leaf
    #       #   mgmt_ip: 100.64.201.4
    #       # - name: DC1-LEAF2
    #       #   serialNumber: 9KS1O7CNJJG
    #       #   role: leaf
    #       #   mgmt_ip: 100.64.201.5
    #       - name: DC1-ABGW1
    #         serialNumber: 9K49T1EJVL1
    #         role: "Border Gateway"
    #         mgmt_ip: 100.64.201.6
    #       - name: DC1-ABGW2
    #         serialNumber: 9T3ILDL95HJ
    #         role: "Border Gateway"
    #         mgmt_ip: 100.64.201.7
    #   include_tasks: inner.yaml
    #   loop: "{{switches}}"
    #   loop_control:
    #     loop_var: switch
    - name: Add Switches to DC2
      vars:
        dc_num: 2
        password: "C!sco123"
        switches:
          - name: DC2-VBGW1
            serialNumber: 9LX3N37XJ76
            role: "border gateway"
            mgmt_ip: 100.64.201.66
          # - name: DC2-VBGW2
          #   serialNumber: 9F1CK93TQKZ
          #   role: "border gateway"
          #   mgmt_ip: 100.64.201.67
      include_tasks: inner.yaml
      loop: "{{switches}}"
      loop_control:
        loop_var: switch
